name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Checkout createPng repository
        uses: actions/checkout@v2
        with:
          repository: OmerJuve2023/CreatePDF
      
      - name: Install createPng dependency
        run: mvn install:install-file -Dfile=target/createPng.jar -DgroupId=org.example -DartifactId=createPng -Dversion=1.0 -Dpackaging=jar
        working-directory: CreatePDF

      - name: Build with Maven
        run: mvn clean install
