name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Checkout createPng repository
        uses: actions/checkout@v2
        with:
          repository: https://github.com/OmerJuve2023/CreatePDF.git
          path: path/to/createPng

      - name: Compile and package createPng
        run: |
          cd path/to/createPng
          mvn clean package
        working-directory: path/to/createPng

      - name: Install createPng dependency
        run: mvn install:install-file -Dfile=path/to/createPng/target/createPng.jar -DgroupId=org.example -DartifactId=createPng -Dversion=1.0 -Dpackaging=jar

      - name: Build with Maven
        run: mvn clean install
